In [ ]:
#Assignment 1
import numpy as np
import pandas as pd

# Task 1 create a pandas dataframe(Dataframe name as 'df') with numpy random values (4 features and 4 observations)
data = np.random.rand(4, 4)
df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'])
df
# Task 2 (Already done in Task 1)  Rename the task-1 'df' dataframe coulmn names to 'Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.992720        0.365287        0.141035        0.988659
1        0.501226        0.179689        0.684058        0.986834
2        0.000209        0.572657        0.880663        0.248751
3        0.056862        0.547008        0.875516        0.335265

In [ ]:
# Task 3 Find the descriptive statistics of the 'df' dataframe
desc_stats = df.describe()
desc_stats

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.387754        0.416160        0.645318        0.639877
std          0.461353        0.182683        0.348416        0.403235
min          0.000209        0.179689        0.141035        0.248751
25%          0.042699        0.318887        0.548302        0.313637
50%          0.279044        0.456147        0.779787        0.661050
75%          0.624100        0.553420        0.876803        0.987290
max          0.992720        0.572657        0.880663        0.988659

In [ ]:
# Task 4 Check for the null values in 'df' and find the data type of the columns
nullvalues = df.isnull().sum()
datatypes = df.dtypes
print(nullvalues)
print(datatypes)

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64
Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
# Task 5 Display the  'Random value 2' and 'Random value 3' columns with location method and index location method
value2_loc = df.loc[:, 'Random value 2']
value3_loc = df.loc[:, 'Random value 3']
print(value2_loc)
print(value3_loc)

0    0.365287
1    0.179689
2    0.572657
3    0.547008
Name: Random value 2, dtype: float64
0    0.141035
1    0.684058
2    0.880663
3    0.875516
Name: Random value 3, dtype: float64

In [ ]:
value2_index_location = df.iloc[:, 1]
value3_index_location = df.iloc[:, 2]
print(value2_index_location)
print(value3_index_location)

0    0.365287
1    0.179689
2    0.572657
3    0.547008
Name: Random value 2, dtype: float64
0    0.141035
1    0.684058
2    0.880663
3    0.875516
Name: Random value 3, dtype: float64